=== 810/Kunena-1.6/administrator/components/com_kunena/install/kunena16.dtd
<?xml version="1.0" encoding="utf-8"?>
<!--
  Kunena install file DTD

  @version      $Id$
  @package		Kunena
  @subpackage	com_kunena
  @copyright	Copyright (C) 2008 - 2009 Kunena Team. All rights reserved.
  @license		GNU General Public License <http://www.gnu.org/copyleft/gpl.html>
  @link			http://www.kunena.com
-->

<!ELEMENT schema (table*)>

<!ELEMENT table (field*, key*)>
<!ATTLIST table 
name ID #REQUIRED
action (none|create|alter|drop) #IMPLIED>

<!ELEMENT field EMPTY>
<!ATTLIST field 
primary_key CDATA #IMPLIED
name CDATA #REQUIRED
type CDATA #REQUIRED
null (0|1) #REQUIRED
default CDATA ""
extra CDATA #IMPLIED
action (none|create|alter|drop) #IMPLIED>

<!ELEMENT key EMPTY>
<!ATTLIST key 
name CDATA #REQUIRED
unique (0|1) #IMPLIED
columns CDATA #IMPLIED
action (none|create|alter|drop) #IMPLIED>

=== 810/Kunena-1.6/administrator/components/com_kunena/install/install.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE schema SYSTEM "kunena16.dtd">
<schema>
  <table name="kunena_announcement">
    <field name="id" type="int(3)" null="0" extra="auto_increment"/>
    <field name="title" type="tinytext" null="0"/>
    <field name="sdescription" type="text" null="0"/>
    <field name="description" type="text" null="0"/>
    <field name="created" type="datetime" null="0" default="0000-00-00 00:00:00"/>
    <field name="published" type="tinyint(1)" null="0" default="0"/>
    <field name="params" type="text" null="0"/>
    <key name="PRIMARY" unique="1" columns="id"/>
  </table>
  <table name="kunena_attachments">
    <field name="id" type="int(11)" null="0" extra="auto_increment"/>
    <field name="msgid" type="int(11)" null="0" default="0"/>
    <field name="filelocation" type="text" null="0"/>
    <field name="params" type="text" null="0"/>
    <key name="PRIMARY" unique="1" columns="id"/>
    <key name="msgid" columns="msgid"/>
  </table>
  <table name="kunena_categories">
    <field name="id" type="int(11)" null="0" extra="auto_increment"/>
    <field name="parent" type="int(11)" null="1" default="0"/>
    <field name="name" type="tinytext" null="1"/>
    <field name="emoticon" type="tinyint(4)" null="0" default="0"/>
    <field name="locked" type="tinyint(4)" null="0" default="0"/>
    <field name="moderators" type="tinytext" null="1"/>
    <field name="pub_access" type="tinyint(4)" null="1" default="1"/>
    <field name="admin_access" type="tinyint(4)" null="1" default="0"/>
    <field name="ordering" type="tinyint(4)" null="0" default="0"/>
    <field name="published" type="tinyint(4)" null="0" default="0"/>
    <field name="review" type="tinyint(4)" null="0" default="0"/>
    <field name="description" type="text" null="0"/>
    <field name="headerdesc" type="text" null="0"/>
    <field name="thread_count" type="mediumint(8)" null="0" default="0"/>
    <field name="message_count" type="mediumint(8)" null="0" default="0"/>
    <field name="last_msgid" type="int(10)" null="0" default="0"/>
    <field name="last_msgtime" type="int(11)" null="1"/>
    <field name="params" type="text" null="0"/>
    <key name="PRIMARY" unique="1" columns="id"/>
    <key name="parent" columns="parent"/>
    <key name="published_pubaccess_id" columns="published,pub_access,id"/>
    <key name="last_msgid" columns="last_msgid"/>
  </table>
  <table name="kunena_threads">
    <field name="id" type="int(11)" null="0" extra="auto_increment"/>
    <field name="catid" type="int(11)" null="0" default="0"/>
    <field name="subject" type="tinytext" null="1"/>
    <field name="emoticon" type="int(11)" null="0" default="0"/>
    <field name="locked" type="tinyint(4)" null="0" default="0"/>
    <field name="hold" type="tinyint(4)" null="0" default="0"/>
    <field name="ordering" type="int(11)" null="0" default="0"/>
    <field name="posts" type="int(11)" null="0" default="0"/>
    <field name="hits" type="int(11)" null="0" default="0"/>
    <field name="attachments" type="int(11)" null="0" default="0"/>
    <field name="moved_id" type="int(11)" null="0" default="0"/>
    <field name="first_post_id" type="int(11)" null="0" default="0"/>
    <field name="first_post_time" type="int(11)" null="0" default="0"/>
    <field name="first_post_userid" type="int(11)" null="0" default="0"/>
    <field name="first_post_message" type="text" null="1"/>
    <field name="last_post_id" type="int(11)" null="0" default="0"/>
    <field name="last_post_time" type="int(11)" null="0" default="0"/>
    <field name="last_post_userid" type="int(11)" null="0" default="0"/>
    <field name="last_post_message" type="text" null="1"/>
    <field name="params" type="text" null="0"/>
    <key name="PRIMARY" unique="1" columns="id"/>
    <key name="catid" columns="catid"/>
    <key name="first_post_userid" columns="first_post_userid"/>
    <key name="last_post_userid" columns="last_post_userid"/>
    <key name="first_post_time" columns="first_post_time"/>
    <key name="last_post_time" columns="last_post_time"/>
    <key name="locked" columns="locked"/>
  </table>
  <table name="kunena_user_threads">
    <field name="thread" type="int(11)" null="0" default="0"/>
    <field name="userid" type="int(11)" null="0" default="0"/>
    <field name="messages" type="mediumint(8)" null="0" default="0"/>
    <field name="id_last_msg" type="int(10)" null="0" default="0"/>
    <field name="favorite" type="tinyint(4)" null="0" default="0"/>
    <field name="subscription" type="tinyint(4)" null="0" default="0"/>
    <field name="params" type="text" null="0"/>
    <key name="thread" unique="1" columns="thread,userid"/>
    <key name="userid" columns="userid"/>
  </table>
  <table name="kunena_messages">
    <field name="id" type="int(11)" null="0" extra="auto_increment"/>
    <field name="parent" type="int(11)" null="1" default="0"/>
    <field name="thread" type="int(11)" null="1" default="0"/>
    <field name="userid" type="int(11)" null="0" default="0"/>
    <field name="markup" type="tinyint(4)" null="0" default="0"/>
    <field name="subject" type="tinytext" null="1"/>
    <field name="message" type="text" null="1"/>
    <field name="time" type="int(11)" null="0" default="0"/>
    <field name="ip" type="varchar(15)" null="1"/>
    <field name="hold" type="tinyint(4)" null="0" default="0"/>
    <field name="ordering" type="int(11)" null="1" default="0"/>
    <field name="modified_by" type="int(7)" null="1"/>
    <field name="modified_time" type="int(11)" null="1"/>
    <field name="modified_reason" type="tinytext" null="1"/>
    <field name="params" type="text" null="0"/>
    <key name="id" unique="1" columns="id"/>
    <key name="thread" columns="thread"/>
    <key name="parent" columns="parent"/>
    <key name="ip" columns="ip"/>
    <key name="userid" columns="userid"/>
    <key name="time" columns="time"/>
    <key name="hold_time" columns="hold,time"/>
  </table>
  <table name="kunena_moderation">
    <field name="catid" type="int(11)" null="0" default="0"/>
    <field name="userid" type="int(11)" null="0" default="0"/>
    <key name="PRIMARY" unique="1" columns="catid,userid"/>
  </table>
  <table name="kunena_ranks"> <!-- REMOVE? -->
    <field name="rank_id" type="mediumint(8) unsigned" null="0" extra="auto_increment"/>
    <field name="rank_title" type="varchar(255)" null="0"/>
    <field name="rank_min" type="mediumint(8) unsigned" null="0" default="0"/>
    <field name="rank_special" type="tinyint(1) unsigned" null="0" default="0"/>
    <field name="rank_image" type="varchar(255)" null="0"/>
    <key name="PRIMARY" unique="1" columns="rank_id"/>
  </table>
  <table name="kunena_smileys"> <!-- REMOVE? -->
    <field name="id" type="int(4)" null="0" extra="auto_increment"/>
    <field name="code" type="varchar(12)" null="0"/>
    <field name="location" type="varchar(50)" null="0"/>
    <field name="greylocation" type="varchar(60)" null="0"/>
    <field name="emoticonbar" type="tinyint(4)" null="0" default="0"/>
    <key name="PRIMARY" unique="1" columns="id"/>
  </table>
  <table name="kunena_users">
    <field name="id" type="int(11)" null="0" default="0"/>
    <field name="moderator" type="int(11)" null="1" default="0"/>
    <field name="ordering" type="int(11)" null="1" default="0"/>
    <field name="posts" type="int(11)" null="1" default="0"/>
    <field name="hits" type="int(11)" null="1" default="0"/>
    <field name="rank" type="tinyint(4)" null="0" default="0"/>
    <field name="hide_email" type="tinyint(1)" null="0" default="1"/>
    <field name="show_online" type="tinyint(1)" null="0" default="1"/>
    <field name="allowed_categories" type="text" null="1"/> <!-- REMOVE? -->
    <field name="read_topics" type="text" null="1"/> <!-- REMOVE? -->
    <field name="last_visit_time" type="int(11)" null="0" default="0"/>
    <field name="curr_visit_time" type="int(11)" null="0" default="0"/>
    <field name="rating" type="int(11)" null="1" default="0"/>
    <field name="params" type="text" null="0"/>
    <key name="PRIMARY" unique="1" columns="id"/>
    <key name="posts" columns="posts"/>
    <key name="hits" columns="hits"/>
  </table>
  <table name="kunena_version">
    <field name="id" type="int(11)" null="0" extra="auto_increment"/>
    <field name="version" type="varchar(20)" null="0"/>
    <field name="versiondate" type="date" null="0"/>
    <field name="installdate" type="date" null="0"/>
    <field name="build" type="varchar(20)" null="0"/>
    <field name="versionname" type="varchar(40)" null="1"/>
    <field name="state" type="varchar(32)" null="0" default="unknown"/>
    <key name="PRIMARY" unique="1" columns="id"/>
  </table>
  <table name="kunena_whoisonline">
    <field name="id" type="int(6)" null="0" extra="auto_increment"/>
    <field name="userid" type="int(7)" null="0" default="0"/>
    <field name="time" type="varchar(14)" null="0" default="0"/>
    <field name="item" type="int(6)" null="1" default="0"/>
    <field name="what" type="varchar(255)" null="1" default="0"/>
    <field name="func" type="varchar(50)" null="1"/>
    <field name="do" type="varchar(50)" null="1"/>
    <field name="task" type="varchar(50)" null="1"/>
    <field name="link" type="text" null="1"/>
    <field name="userip" type="varchar(20)" null="0"/>
    <field name="user" type="tinyint(2)" null="0" default="0"/>
    <key name="PRIMARY" unique="1" columns="id"/>
    <key name="userid" columns="userid"/>
  </table>
  <table name="kunena_log">
    <field name="id" type="int(11)" null="0" extra="auto_increment"/>
    <field name="timestamp" type="datetime" null="0" default="0000-00-00 00:00:00"/>
    <field name="userid" type="int(11)" null="0" default="0"/>
    <field name="ip" type="varchar(40)" null="0"/>
    <field name="cookie" type="varchar(40)" null="0"/>
    <field name="action" type="int(6)" null="0" default="0"/>
    <field name="catid" type="int(11)" null="0" default="0"/>
    <field name="msgid" type="int(11)" null="0" default="0"/>
